spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "12345678"
    url: jdbc:mysql://localhost:3306/goldwind?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  kafka:
    bootstrap-servers: 10.80.12.82:9092
    producer:
      acks: 1
      batch-size: 131072
      linger.ms: 100
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: concurrent-client
      enable-auto-commit: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml

factory-config:
  client-config:
    type: socket
    protocol: udp
    amount: 1
    proxyIP: 127.0.0.1
    proxyPort: 8081
    appIP: 127.0.0.1
    appPort: 10727
  data-config:
    type: byte
    path:
    size: 1024
  channel-config:
    type: single